steps:
  - name: "gcr.io/cloud-builders/docker"
    script: |
      docker build -f Dockerfile.image.job -t us-west2-docker.pkg.dev/$PROJECT_ID/guac-jobs/upload-waka-image:v0.0.1 .
    automapSubstitutions: true
images:
  - "us-west2-docker.pkg.dev/$PROJECT_ID/guac-jobs/upload-waka-image:v0.0.1"
