FROM golang:1.23 as base
WORKDIR /go/src/app
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
RUN go build -o /go/bin/job ./cmd/jobs/main.go

FROM golang:1.23
COPY --from=base /go/bin/job /go/bin/job
CMD ["/go/bin/job"]
