name: Persist WakaTime

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * MON"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: go build -o persist cmd/persister/main.go

      - name: Run
        run: ./persist
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          API_KEY: ${{ secrets.API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DYNAMO_TABLE: ${{ secrets.DYNAMO_TABLE }}
          DYNAMO_REGION: ${{ secrets.DYNAMO_REGION }}


